version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki
      - tempo
      - alertmanager

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200"   # Tempo API
      # - "4319:4317"   # OTLP gRPC receiver
      # - "4318:4318"   # OTLP HTTP receiver
      - "14319:4319"  # map container’s 4319 to host’s 14319
      - "14318:4318"  # optional http
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  # promtail:
    # image: grafana/promtail
    # container_name: promtail
    # ports:
      # - "9080:9080"
    # command: -config.file=/etc/promtail/promtail.yml
    # volumes:
      # - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      

  