services:
  # http://localhost:8080/
  termix:
    # image: ghcr.io/lukegus/termix:latest
    image: bugattiguy527/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - termix-data:/app/data
    environment:
      PORT: "8080"

volumes:
  termix-data:
    driver: local