global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Scrape Loki metrics
  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  # Scrape Tempo metrics
  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]

  # Scrape Promtail metrics
  - job_name: promtail
    static_configs:
      - targets: ["promtail:9080"]
      
  - job_name: 'windows-metrics'
    static_configs:
      - targets: ['host.docker.internal:8889']
